//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetPro2019.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TFDBEntities : DbContext
    {
        public TFDBEntities(string entity)
            : base("name="+entity)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PGPS_Application> PGPS_Application { get; set; }
        public DbSet<PGPS_ApplicationModule> PGPS_ApplicationModule { get; set; }
        public DbSet<PGPS_Module> PGPS_Module { get; set; }
        public DbSet<PGPS_SystemUser> PGPS_SystemUser { get; set; }
        public DbSet<PGPS_UserLogs> PGPS_UserLogs { get; set; }
    
        public virtual ObjectResult<sp_PGPS_get_roles_list_Result> sp_PGPS_get_roles_list(Nullable<int> rolevalue)
        {
            var rolevalueParameter = rolevalue.HasValue ?
                new ObjectParameter("rolevalue", rolevalue) :
                new ObjectParameter("rolevalue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PGPS_get_roles_list_Result>("sp_PGPS_get_roles_list", rolevalueParameter);
        }
    }
}
